### ISSUE TITLE
HA Update 2025. 8.2 no integration available anymore

### ISSUE THREAD

**Issue by Ripper6666** [ChrisHaPunkt/ha-stihl-imow#32]
After HA update to Version 2025.8.2 the integration no longer shows any values

<img width="935" height="690" alt="Image" src="https://github.com/user-attachments/assets/dbb37bcf-22ed-49bd-b814-c0a1ef668cce" />

How can I fix this? 
Request for support. :-)

**Comment by ChrisHaPunkt** [comment]
Still working on my 2025.8.2

![Screenshot_20250818-145344.png](https://github.com/user-attachments/assets/b6f7ea58-4ec2-41f6-b961-7459633ce7e2)

Did you restart?

**Comment by Ripper6666** [comment]
Jup,restart done,but no change

**Comment by ChrisHaPunkt** [comment]
Is there any related error in the logs?

**Comment by Ripper6666** [comment]
Logger: homeassistant.config_entries
Quelle: config_entries.py:749
Erstmals aufgetreten: 10:00:03 (3 Vorkommnisse)
Zuletzt protokolliert: 15:13:08

Error setting up entry Lawn Mower for stihl_imow
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/imow/api/__init__.py", line 237, in __fetch_new_csrf_token_and_request_id
    ).get("value")
      ^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stihl_imow/__init__.py", line 53, in async_setup_entry
    await imow_api.get_token(force_reauth=True)
  File "/usr/local/lib/python3.13/site-packages/imow/api/__init__.py", line 139, in get_token
    await self.__authenticate(self.api_email, self.api_password)
  File "/usr/local/lib/python3.13/site-packages/imow/api/__init__.py", line 190, in __authenticate
    await self.__fetch_new_csrf_token_and_request_id()
  File "/usr/local/lib/python3.13/site-packages/imow/api/__init__.py", line 242, in __fetch_new_csrf_token_and_request_id
    raise ProcessLookupError(
        "Did not find necessary csrf token and/or request id in html source"
    )
ProcessLookupError: Did not find necessary csrf token and/or request id in html source


does that help?

**Comment by Ripper6666** [comment]
I completely re-downloaded the integration and deactivated the old one. 
After reinstalling, HA restart, the integration works again.
Anyway, thank you very much for your support!!
